name: Release (beta)

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: nestjs

jobs:
  release-candidate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Generate changelog
        run: yarn run standard-version

      - name: Get release version
        id: 'release-version'
        uses: martinbeentjes/npm-get-version-action@main

      - name: Get release branch
        id: 'release-branch'
        run: echo "RELEASE_BRANCH={release-${{ steps.release-version.outputs.current-version}}" >> $GITHUB_OUTPUT


      - name: Create release branch
        run: git checkout -b ${{ steps.release-branch.outputs.RELEASE_BRANCH }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: main
          base: ${{ steps.release-branch.outputs.RELEASE_BRANCH }}
          title: 'Release ${{ steps.release-version.outputs.current-version }}'
          body: |
            Update report
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request

